import { SceneName } from './enums/SceneNames';
import { Door } from './components/Door';
import { drawDoorCue } from './components/DoorCue';
import { CollisionStrategy } from 'grid-engine';
import GameScene from "./GameScene"
import { LayerType } from './enums/LayerType';
import { MAPS } from '../data/maps';

// The Elementals that live outdoors in town. Neon roams the plaza like a glowing
// sign. Oxygen and Nitrogen live wild up in the North Woods; Hydrogen and Carbon
// have moved down into the Museum basement (in the city). The rest live inside the
// venues. Coordinates are walkable grass, clear of paths/lake.
const MONSTER_SPAWNS: { elementId: string; x: number; y: number }[] = [
    { elementId: 'neon',     x: 16, y: 14 },
];

// Each venue's walkable door tile (bottom of the painted doorway) and the room
// it leads into. Generated by tools/gen_town.py — keep in sync with its
// printed "door tiles". Gray, Maine (04039) storefronts.
const TOWN_DOORS: { x: number; y: number; scene: SceneName }[] = [
    { x: 5,  y: 8,  scene: SceneName.Hardware },
    { x: 15, y: 8,  scene: SceneName.Hannaford },
    { x: 24, y: 8,  scene: SceneName.Library },
    { x: 34, y: 8,  scene: SceneName.Home },
    { x: 5,  y: 20, scene: SceneName.Auto },
    // North trail out of town → the woods & meadow (walk up the gap between the
    // hardware and grocery stores). Pad is the tile just south, like any door.
    { x: 9,  y: 0,  scene: SceneName.Woods },
];

// Real building art (cropped tight to its content) overlaid on the invisible
// storefront footprints from tools/gen_town.py. Each image is anchored
// bottom-centre over its door tile and scaled so it spans `widthTiles` tiles
// wide; every storefront has its name painted on, so no sign plaques are needed.
// The wide storefronts are sized up so they don't look small beside the square
// hardware store — keep widthTiles in sync with WIDTH_TILES in gen_town.py.
const BUILDINGS: { key: string; oy: number; h: number; doorX: number; widthTiles: number }[] = [
    { key: 'bld_hardware', oy: 1,  h: 8, doorX: 5,  widthTiles: 6.3 },
    { key: 'bld_grocery',  oy: 1,  h: 8, doorX: 15, widthTiles: 9.8 },
    { key: 'bld_library',  oy: 1,  h: 8, doorX: 24, widthTiles: 8.6 },
    { key: 'bld_home',     oy: 1,  h: 8, doorX: 34, widthTiles: 9.8 },
    { key: 'bld_auto',     oy: 13, h: 8, doorX: 5,  widthTiles: 9.8 },
];

// The decorative lake (matches LAKE in tools/gen_town.py): a rectangle of
// blocking water cells. Painted here with the canonical jungle/oasis water
// texture (tools/slice_water.py) so water reads the same in every zone.
const LAKE = { x: 24, y: 15, w: 14, h: 7 };  // in tiles
const WATER_TEX = 'water_tex';


export default class TestScene extends GameScene {
    constructor() {
        super(SceneName.Test, 18, 12, [LayerType.Floor, LayerType.Walls])

        this.imageNames = {
            Perli: `${SceneName.Test}_perli`,
            Veterinary: 'test_veterinary',
            Map: 'test_map',
        }

        this.tilemapJSONPath = 'assets/tilemap/test_map.json'
        this.imageMapDefaultPath = 'assets/tiles/'
        this.mapData = MAPS.test_map
        this.imageMapNames = {
            modern_exterior: {
                name: "modern_exterior",
            },
        }

        this.gridEngineSettings = {
            startPosition: {
                x: 18,
                y: 12
            },
            scale: 5,
            characterCollisionStrategy: CollisionStrategy.BLOCK_ONE_TILE_AHEAD,
            layerOverlay: false
        }
    }

    preload(): void {
        super.preload()
        super.loadAvatarSpritesheet()
        super.loadMapImages()
        this.loadObjectImages()
    }

    loadObjectImages(): void {
        this.load.spritesheet(
            this.imageNames.Veterinary,
            'assets/Characters/NPCs_1.png',
            {
                frameWidth: 32,
                frameHeight: 64
            }
        )
        this.loadElementalArt(MONSTER_SPAWNS.map(s => s.elementId))
        // Storefront art (backgrounds already removed) overlaid on the map.
        BUILDINGS.forEach(b => this.load.image(b.key, `assets/buildings/${b.key.replace('bld_', '')}.png`))
        // Canonical shared water tile (the jungle's) for the lake — see drawLake.
        this.load.image(WATER_TEX, 'assets/tiles/water.png')
    }

    create(): void {
        super.create()

        // The town lake — blue water behind the sprites (real tiles have no
        // water art, so we paint it). The cells are already blocking (gen_town).
        this.drawLake()

        // Real storefront art over the invisible building footprints.
        BUILDINGS.forEach(b => this.drawBuilding(b))

        // One door per building: step onto the square outside it (one tile south)
        // to enter. A glowing "ENTER ▲" pad marks each entrance so new players can
        // tell buildings are enterable — most Elementals live inside them.
        TOWN_DOORS.forEach(d => {
            new Door({
                scene: this, xPosition: d.x, yPosition: d.y, nextScene: d.scene
            })
            const label = d.scene === SceneName.Woods ? 'WOODS' : 'ENTER'
            drawDoorCue(this, d.x, d.y + 1, label, '▲')
        })
    }

    // Overlay one storefront image: anchored bottom-centre on its door tile and
    // scaled so the art spans `widthTiles` tiles wide (aspect preserved). Depth 1
    // keeps it above the ground tiles but below the characters (depth 10), so the
    // dog walks in front of the shop.
    private drawBuilding(b: { key: string; oy: number; h: number; doorX: number; widthTiles: number }): void {
        const src = this.textures.get(b.key).getSourceImage() as HTMLImageElement
        const scale = (b.widthTiles * 16) / src.width
        this.add.image((b.doorX + 0.5) * 16, (b.oy + b.h) * 16, b.key)
            .setOrigin(0.5, 1)
            .setScale(scale)
            .setDepth(1)
    }

    // Paints the lake: the canonical jungle/oasis water texture tiled over the
    // blocking water cells (so water looks the same here as in the jungle and
    // desert), clipped to a rounded-rect pond shape with a dark-teal rim, plus a
    // "LAKE" label. Sits above the ground tiles but below the floating labels;
    // the dog can never walk onto it (those cells collide), so depth is safe.
    private drawLake(): void {
        const px = LAKE.x * 16, py = LAKE.y * 16, pw = LAKE.w * 16, ph = LAKE.h * 16
        const water = this.add.tileSprite(px, py, pw, ph, WATER_TEX)
            .setOrigin(0, 0).setDepth(50)
        // Rounded-rect geometry mask → the stylised pond shape (grass shows in the
        // corners, as before). make.graphics is kept off the display list.
        const maskShape = this.make.graphics({ x: 0, y: 0 }, false)
            .fillStyle(0xffffff).fillRoundedRect(px, py, pw, ph, 10)
        water.setMask(maskShape.createGeometryMask())
        this.add.graphics().setDepth(50)
            .lineStyle(2, 0x2c4b47, 1).strokeRoundedRect(px, py, pw, ph, 10)
        this.add.text(px + pw / 2, py + ph / 2, 'LAKE', {
            fontFamily: 'monospace',
            fontSize: '12px',
            fontStyle: 'bold',
            color: '#eaf4ff',
        }).setOrigin(0.5).setDepth(51)
    }

    createNpcs(): void {
        // One Elemental per outdoor spawn — real art if it has any, else a tinted
        // placeholder. Walk within one tile to start its quiz (see spawnElemental).
        MONSTER_SPAWNS.forEach(spawn => this.spawnElemental(spawn.elementId, spawn.x, spawn.y));
    }

    update(): void {
        super.update()
    }
}