// Embed the Tiled tilemap JSONs into a TS module so the game loads with no XHR
// (works from a plain file:// double-click, not just a web server).
// Re-run after regenerating any map: node tools/embed-maps.mjs
import { readFileSync, writeFileSync } from 'fs';

const maps = ['test_map', 'woods_map', 'interior_room', 'city_map', 'city_interior',
    'museum_ground', 'museum_b1', 'museum_b2', 'museum_b3', 'museum_b4',
    'room_finance', 'room_large_tower', 'room_church', 'room_fashion',
    'room_power_tower', 'room_radio_tower', 'room_power_station', 'room_radio_tower2',
    'room_cafe', 'room_library', 'room_home', 'room_treats'];
const entries = maps.map(m => {
    // Normalize the (unused) tileset image paths so the bundle has no ../assets.
    const json = readFileSync(`src/assets/tilemap/${m}.json`, 'utf8').trim()
        .replace(/\.\.\/assets/g, 'assets');
    return `    ${m}: ${json},`;
}).join('\n');

const out = `// AUTO-GENERATED by tools/embed-maps.mjs from src/assets/tilemap/*.json.
// Embedding the tilemaps lets the game run offline from file:// (no XHR).
/* eslint-disable */
export const MAPS: Record<string, any> = {
${entries}
};
`;
writeFileSync('src/data/maps.ts', out);
console.log('wrote src/data/maps.ts with', maps.length, 'maps');
