// AUTO-GENERATED by tools/gen_museum_collision.py from the painted
// /home/nah/museum-collision/*_PAINT-ME.png masks. Do not edit by hand.
// Portal `type` -> target is resolved in CityInteriorScene: ascend=cfg.up,
// descend=cfg.down, custom=Cloud City.
/* eslint-disable */
export interface MuseumPortal { type: 'ascend' | 'descend' | 'custom'; x: number; y: number; }
export interface MuseumFloorNav { start: { x: number; y: number }; portals: MuseumPortal[]; }
export const MUSEUM_NAV: Record<string, MuseumFloorNav> = {
    museum_ground: { start: { x: 11, y: 6 }, portals: [{ type: 'descend', x: 4, y: 1 }, { type: 'descend', x: 5, y: 1 }, { type: 'descend', x: 16, y: 1 }, { type: 'descend', x: 17, y: 1 }, { type: 'descend', x: 4, y: 2 }, { type: 'descend', x: 5, y: 2 }, { type: 'descend', x: 16, y: 2 }, { type: 'descend', x: 17, y: 2 }, { type: 'ascend', x: 10, y: 10 }, { type: 'ascend', x: 11, y: 10 }] },
    museum_b1: { start: { x: 11, y: 6 }, portals: [{ type: 'ascend', x: 1, y: 1 }, { type: 'descend', x: 10, y: 1 }, { type: 'descend', x: 11, y: 1 }, { type: 'descend', x: 10, y: 2 }, { type: 'descend', x: 11, y: 2 }, { type: 'descend', x: 10, y: 3 }, { type: 'descend', x: 11, y: 3 }] },
    museum_b2: { start: { x: 11, y: 6 }, portals: [{ type: 'descend', x: 17, y: 1 }, { type: 'descend', x: 18, y: 1 }, { type: 'descend', x: 17, y: 2 }, { type: 'descend', x: 18, y: 2 }, { type: 'descend', x: 17, y: 3 }, { type: 'descend', x: 18, y: 3 }, { type: 'descend', x: 17, y: 4 }, { type: 'descend', x: 18, y: 4 }, { type: 'ascend', x: 1, y: 10 }] },
    museum_b3: { start: { x: 11, y: 6 }, portals: [{ type: 'descend', x: 17, y: 1 }, { type: 'descend', x: 18, y: 1 }, { type: 'custom', x: 4, y: 2 }, { type: 'custom', x: 5, y: 2 }, { type: 'descend', x: 17, y: 2 }, { type: 'descend', x: 18, y: 2 }, { type: 'custom', x: 4, y: 3 }, { type: 'custom', x: 5, y: 3 }, { type: 'descend', x: 17, y: 3 }, { type: 'descend', x: 18, y: 3 }, { type: 'descend', x: 17, y: 4 }, { type: 'descend', x: 18, y: 4 }, { type: 'ascend', x: 1, y: 10 }] },
    museum_b4: { start: { x: 11, y: 7 }, portals: [{ type: 'ascend', x: 1, y: 10 }] },
};
